# Build MS Project / Azure DevOps add-in (AzDOAddIn)
# Builds the solution and publishes add-in output for deployment.

trigger:
  branches:
    include:
      - main
      - master
  paths:
    include:
      - AzDOAddIn/**
      - azure-pipelines.yml

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'AzDOAddIn/AzDOAddIn.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Use NuGet'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    msbuildArguments: '/p:RestorePackagesConfig=true'

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  continueOnError: true

- task: CopyFiles@2
  displayName: 'Copy add-in artifacts'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/AzDOAddIn/AzDOAddIn/bin/$(buildConfiguration)'
    Contents: '**/*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/AzDOAddIn'
  condition: succeeded()

- task: PublishBuildArtifacts@1
  displayName: 'Publish add-in artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/AzDOAddIn'
    ArtifactName: 'AzDOAddIn'
    publishLocation: 'Container'
  condition: succeeded()
